META_ARC: "siamrpn_alex_dwxcorr"

BACKBONE:
    TYPE: "alexnet_lite"
    KWARGS:
        width_mult: 0.25
    PRETRAINED: ''
    TRAIN_LAYERS: ['layer1', 'layer2', 'layer3', 'layer4']
    TRAIN_EPOCH: 10
    LAYERS_LR: 1.0

ADJUST:
    ADJUST: False

RPN:
    TYPE: 'DepthwiseRPN'
    KWARGS:
        anchor_num: 4
        in_channels: 64
        out_channels: 64

MASK:
    MASK: False

ANCHOR:
    STRIDE: 8
    RATIOS: [0.3, 0.5, 1, 2]
    SCALES: [8]
    ANCHOR_NUM: 4

TRACK:
    TYPE: 'SiamRPNTracker'
    PENALTY_K: 0.16
    WINDOW_INFLUENCE: 0.40
    LR: 0.30
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 287
    BASE_SIZE: 0
    CONTEXT_AMOUNT: 0.5

TRAIN:
    EPOCH: 35
    START_EPOCH: 0
    BATCH_SIZE: 128
    BASE_SIZE: 0
    OUTPUT_SIZE: 17
    EXEMPLAR_SIZE: 127
    SEARCH_SIZE: 255
    BASE_LR: 0.005
    CLS_WEIGHT: 1.
    LOC_WEIGHT: 1.2
    RESUME: '' # '/home/pdl/yjk/pysot/pretrained_models/model.pth'

    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.01
            end_lr: 0.0005
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.005
            end_lr: 0.01
            step: 1

DATASET:
    NAMES:
    - 'COCO'

    TEMPLATE:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.05
    GRAY: 0.0